### ISSUE TITLE
No delegate tutorial

### ISSUE THREAD

**Issue by marcin-trust** [safe-global/safe-docs#150]
This page https://docs.gnosis-safe.io/tutorials/tutorial_tx_service_initiate_sign contains a link to delegate tutorial:
https://github.com/gnosis/safe-docs/tree/98cffd3359a173173543997a027134572e00cf29/tutorials/tutorial_tx_service_set_delegate.md

which does not exist anymore.

Could you point me to a new location or has the delegation feature been deprecated?

**Comment by sche** [comment]
@marcin-trust delegates feature was not deprecated. It is a broken link. We will fix it.
You can find an older version [here](https://github.com/gnosis/safe-docs/blob/v1.0.28/docs/tutorial_tx_service_set_delegate.md)

**Comment by Soptq** [comment]
Hi @marcin-trust , if you just want to set up a delegator, then https://github.com/Soptq/gnosis-safe-delegate-dapp might help which provides a web interface for delegation. However, it doesn't support making transactions etc.
