### ISSUE TITLE
wrong title and dead link

### ISSUE THREAD

**Issue by yash251** [safe-global/safe-docs#162]
https://github.com/safe-global/safe-docs/blob/main/learn/safe-tools/untitled.md

Here untitled.md should be web.md and inside the file "https://www.gnosis-safe.io/app/rinkeby" 👈🏻 this link is present which is 404

**Comment by dasanra** [comment]
@yash251 thank you for your ticket

This has been solved
https://github.com/safe-global/safe-docs/blob/main/learn/web.md

**Comment by yash251** [comment]
hey @dasanra . I applied for Tech Community Manager, had a talk with Jenna and got rejected due to less experience. Actally I was very much aligned with the role, I also have a list of what currently Safe is lacking and how I can come in and bridge those differences.
