### ISSUE TITLE
Goerli testnet deprecated

### ISSUE THREAD

**Issue by mhmmdhajizade** [safe-global/safe-docs#214]
Hi,
I want to deploy a dapp that is Ethereum based. For testing purposes, I want to use Testnet but the only Testnet available in safe services is Goerli which will be deprecated until the end of the year and already has many problems to use. I wanted to know if there are going to be any Testnet chains in available services soon.

**Comment by germartinez** [comment]
Hi,
We will support Sepolia before Goerli is deprecated.
