### ISSUE TITLE
Compatibility issues with web3auth >4.0.0 for auth kit

### ISSUE THREAD

**Issue by SaratAngajalaoffl** [safe-global/safe-docs#241]
![image](https://github.com/safe-global/safe-docs/assets/60383339/b1cc0ce3-d865-4d6c-bcc3-178d04a2a41a)

The code snippet above provided in the docs on the auth-kit section installs the latest version of web3auth i.e. v7. v7 is not compatible with safe libraries and is throwing errors. Would be helpful if the supported web3auth version i.e v4 is mentioned in the docs

**Comment by tanay1337** [comment]
Thank you so much for reporting this, @SaratAngajalaoffl! You are a star 🌟
