### ISSUE TITLE
Sequence diagram view not visible on the docs page

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-docs#288]
**Describe the bug**
Whereas on [Github](https://github.com/safe-global/safe-docs/blob/main/safe-core-api/safe-transaction-service.md#offchain-transaction-signatures) diagrams like the one for the Offchain transaction signatures for the tx-service are displayed as expected:

![Screenshot 2023-11-27 at 17 03 57](https://github.com/safe-global/safe-docs/assets/92332710/1916bf98-e657-4495-aa47-369369190169)

On the Docs [page](https://docs.safe.global/safe-core-api/service-architecture/safe-transaction-service) this and other diagrams following the same structure are not:

![Screenshot 2023-11-27 at 17 05 23](https://github.com/safe-global/safe-docs/assets/92332710/a1e3cb28-e030-44af-9e57-cfb065f7e40b)

**Comment by tanay1337** [comment]
Will be resolved with switch to Nextra.
