### ISSUE TITLE
[Question] How i can use safe-global with my custom network, which don't support in safe-global?

### ISSUE THREAD

**Issue by daniilSapielkin-boostylabs** [safe-global/safe-docs#405]
### Question

[Question] How i can use safe-global with my custom network, which don't support in safe-global?
Fot example i created network in [buildbear](https://home.buildbear.io/) and i want use safe-global with it .
Please tell me what safe-global npm package i need use , and maybe do you have any example for me?

Example where you added custom network and use some functionality , and create simple transaction, it will be very help me

**Comment by louis-md** [comment]
Hi there,

You can deploy safe contracts by following [this guide](https://github.com/safe-global/safe-smart-account/tree/main?tab=readme-ov-file#deploy); once it's done, you can deploy safe-infrastructure by following [this guide](https://github.com/safe-global/safe-infrastructure). Once both are up and running, you should be able to run your fork of app.safe.global using your custom network.

Hope it helps; Best, Louis.
